Update DOI Missing Reason Enumeration Check
DOI Missing Reason Enumeration Check -
"The check works (no error when missing reason ""Not Applicable"" or ""Unknown""; correct error message when any other value listed as missing reason) but when a value other than ""Not Applicable"" or ""Unknown"" is provided, pyQuARC gives another error message under ""DOI"" in addition to the correct error message under ""DOI/MissingReason"" that says:
>> DOI:
                Error: One of `['DOI/DOI', 'DOI/MissingReason']` should be populated.
                Make sure one of the fields is populated.

There is a ""oneOf"" element in the check_messages.json that is giving this message for this field. Working to figure out why this error message is being displayed when an error message is already giving for the Missing Reason being an invalid value."